### ISSUE TITLE
Game crashing whenever I attempt to use the isotope separator.

### ISSUE THREAD

**Issue by Josthompson1** [Chronos-DX/Nucleardustry#2]
I don't know why this is happening, but I can't use the fission reactor because I am in capable of using the isotope reactor.

**Comment by Chrono-Heritage** [comment]
Do you use other mods? Also, can you tell me more detail about how you use it?

**Comment by Josthompson1** [comment]
It might be because of the other mods I'm using, going to try to see if I can isolate the problem, and what I do when I'm using it, I just got a conveyor and fed it uranium. If I'm far away from it it doesn't do anything, but as soon as I get in a range of around 40 tiles radius, my game immediately crashes.

**Comment by Josthompson1** [comment]
Isolated it, Game crash the moment I gave it power for the uranium. I don't know why it's doing this,  my game just immediately crashes.

**Comment by Josthompson1** [comment]
https://youtu.be/4Ma9GEWadTA
Is a link to the video showcasing the problem.

**Comment by Chrono-Heritage** [comment]
I have tested the Isotope Separator on my mobile device and my computer, and I found that the crash only occurs on my mobile device just like you, but I can't really know where the problem is. I will keep testing, and if any new findings, I will tell you here.

**Comment by Chrono-Heritage** [comment]
OK, the problem is I forgot to update the "ambientSound" region, so it cannot load the sound so causing the crash, I fixed it, and it works normally now. Also thanks for playing with this mod!

**Comment by Josthompson1** [comment]
Thanks, and you're welcome!

**Comment by YamiyoshinLevi** [comment]
Conclusion

**Comment by YamiyoshinLevi** [comment]
Conclusion:
It only happen on Mobile.
Because of the game can't find the target sound file.
It also happens on my mod because I have no time to make the sound of Schmitŕov Air Factory.
