### ISSUE TITLE
Radio Liquefier missing texture

### ISSUE THREAD

**Issue by Cowz42** [Chronos-DX/Nucleardustry#4]
The Radio Liquefier is missing its texture for when it is running
![20230106_113630](https://user-images.githubusercontent.com/122100901/211066974-9c299552-3c25-4e55-ae84-82a9eaaf569b.jpg)

**Comment by Chrono-Heritage** [comment]
For this problem, the original drawer has a top region, and I didn't add it, now the region is now added, so it is fixed! Also thanks for playing with this mod!
